import type { Metadata } from "next";

import "./globals.css";
import Header from "@/components/Header";
import Provider from "./Provider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html dir="rtl" lang="fa">
      <head>
        <link
          href="https://cdn.jsdelivr.net/gh/rastikerdar/vazirmatn@v33.003/Vazirmatn-font-face.css"
          rel="stylesheet"
          type="text/css"
        />
      </head>
      <body className={` antialiased`}>
        <Provider>
          <Header />
          <main className="min-h-screen pt-20 container">{children}</main>
        </Provider>
      </body>
    </html>
  );
}
